---
title: "About"
output: 
  distill::distill_article:
    css: styles.css
    includes:
      in_header: favicon.html
---
```{r about-setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

## Data Sources

All data has been gathered from the fitzRoy package, which uses statistics from sources such as AFL tables and Footywire.

## Inspirations and shoutouts

I wanted to give some recognition to who and what has inspired this page, please check them out!

-   Squiggle
-   Wheelo Ratings
-   AFL Tables
-   AFLxScore
-   DFS Australia
-   AFLGlicko
-   BriceMitchell
-   AzzaJewell
-   Jaiden Popowski

## Personal Info

Core Sports Data is a passion project of mine, as well as a portfolio I am trying to build in my free time. I have recently graduated from university, and I have a strong passion for data and sports, and I love combining the two in order to gain further insight into the sports  that I am passionate about. 

### Questions or Feedback?

If you have questions or suggestions for future analysis, please [reach out!](https://x.com/CoreSportsData).